KEYWORD_SEEDS = (
    "how much life insurance do i need",
    "budget for irregular expenses",
    "credit card foreign transaction fee",
    "avoid credit card interest",
    "ach transfer pending",
    "ach transfer time",
    "wire transfer failed",
    "side income tax reporting",
    "crypto tax records",
    "tax loss harvesting holding period",
    "backdoor roth ira taxes",
    "401k contribution limit",
    "roth ira withdrawal rules",
    "pay off parents mortgage",
    "mortgage interest deduction co owners",
    "pay off home equity loan",
    "stolen check close bank account",
    "suspicious credit card charge",
    "bank scam cash withdrawal",
    "sell old stock certificates",
    "where to sell silver",
    "accumulating vs distributing etf",
    "alternative investment strategies",
    "xirr investment calculation",
    "student loan without cosigner",
)
